//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TogglToTimesheet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approver
    {
        public System.Guid Uid { get; set; }
        public string Name { get; set; }
    }
}
