//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TogglToTimesheet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerAssignment
    {
        public int Id { get; set; }
        public string Tag { get; set; }
        public System.Guid ProjectGuid { get; set; }
        public System.Guid TaskGuid { get; set; }
        public System.Guid AssignmentGuid { get; set; }
        public int WorkerId { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
